/*
 * Copyright (C) 2016 Tadesse Angaw
 *
 * This program is written by Tadesse Angaw.
 * You can use and redistribute it without modification.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You can contact me at tadesseangaw@gmai.com
 */
package com.tadesse.bahirehasab.app;

import java.util.Calendar;
import java.util.Locale;
import com.tadesse.bahirehasab.tools.EthiopianCalendar;

/**
 *
 * @author Nabiot
 */
public class AdditionalInfo extends javax.swing.JDialog {

    EthiopianCalendar ec = new EthiopianCalendar();

    /**
     * Creates new form AdditionalInfo
     *
     * @param parent
     * @param modal
     * @param date
     * @param month
     * @param year
     */
    public AdditionalInfo(java.awt.Frame parent, boolean modal, int date, int month, int year) {
        super(parent, modal);
        initComponents();
        additionalInfoBuilder(date, month, year);
        int parentWidth = parent.getWidth();
        int parentX = parent.getX();
        int parentHeight = parent.getHeight();
        int parentY = parent.getY();
        
        pack();
        setLocation((parentWidth / 2) - (getWidth() / 2) + parentX, (parentHeight / 2) - (getHeight() / 2) + parentY);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        fast = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        saint = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        gregorian = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("የዕለቱ መረጃ");

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel4.setText("ጾም :");

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setText("ቀን :");

        year.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        year.setText("Year");

        fast.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        fast.setText("jLabel1");

        day.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        day.setText("jLabel1");

        saint.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        saint.setText("jLabel1");

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel3.setText("የሚታሰበው ቅዱስ :");

        month.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        month.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        month.setText("Month");

        back.setFont(new java.awt.Font("Ebrima", 0, 13)); // NOI18N
        back.setText("ተመለስ");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("Date");

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel5.setText("በጎርጎርዮሳውያን :");

        gregorian.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        gregorian.setText("jLabel1");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(back))
                            .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(month, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(day, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gregorian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(month)
                        .addGap(18, 18, 18)
                        .addComponent(year))
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(day))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saint))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fast))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(gregorian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(back)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void additionalInfoBuilder(int date, int month, int year) {
        this.month.setText(EthiopianCalendar.MONTHS[month]);
        this.date.setText(ec.toEthiopicNumber(date) + " | " + date);
        this.year.setText(ec.toEthiopicNumber(year) + " | " + year);
        day.setText(ec.getDayName(ec.toNumberDay(date, month + 1, year), year));
        saint.setText("<html>" + EthiopianCalendar.SAINTS[date - 1] + "</html>");
        fast.setText(fasting(ec.toNumberDay(date, month + 1, year), year));
        Calendar c = ec.toGregorianDate(date, ++month, year);
        gregorian.setText(c.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.ENGLISH) + " - " + c.get(Calendar.DAY_OF_MONTH) + " - " + c.get(Calendar.YEAR));

    }

    public String fasting(int day, int year) {

        int tsege = ec.getTsege();
        int nebiyat = ec.getTsomeNebiyat();
        int gad = ec.getGad(year);

        int tensae = ec.getTinsae(year);
        int nenewe = ec.getNenewe(year);
        int abey = ec.getAbeyTsome(year);
        int sene = ec.getTsomeHawariyat(year);
        int robarb = ec.getTsomeDihnet(year);
        int felseta = ec.getFelseta();

        if ((day >= tsege) && day < 66) {
            return "ጽጌ ጾም";
        } else if ((day >= nebiyat) && (day < ec.getGena(year))) {
            return "ጾመ ነቢያት";
        } else if ((day == gad)) {
            return "ጋድ";
        } else if ((day >= nenewe) && day < nenewe + 4) {
            return "ጋድ";
        } else if ((day >= abey) && (day < ec.getTinsae(year))) {
            return "ዐቢይ ጾም";
        } else if ((day >= sene) && (day < 305)) {
            return "ጾመ ሐዋርያት";
        } else if ((day >= felseta) && (day < 346)) {
            return "ጾመ ፍልሰታ";
        } else if (!(day >= tensae && day < robarb) && (ec.getDayNumber(day, year) == 2 || ec.getDayNumber(day, year) == 4)) {
            return "ጾመ ድኅነት";
        } else {
            return "ጾም የለውም";
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel date;
    private javax.swing.JLabel day;
    private javax.swing.JLabel fast;
    private javax.swing.JLabel gregorian;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel month;
    private javax.swing.JLabel saint;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
