/*
 * Copyright (C) 2016 Tadesse Angaw
 *
 * This program is written by Tadesse Angaw.
 * You can use and redistribute it without modification.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You can contact me at tadesseangaw@gmail.com
 */
package com.tadesse.bahirehasab.app;

import java.util.Calendar;
import java.util.Locale;
import com.tadesse.bahirehasab.tools.EthiopianCalendar;

/**
 *
 * @author Tadesse Angaw
 */
public class DateConverter extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    String[] MONTHS = new String[]{"መስከረም", "ጥቅምት", "ኅዳር", "ታህሳስ", "ጥር", "የካቲት",
        "መጋቢት", "ሚያዝያ", "ግንቦት", "ሰኔ", "ሐምሌ", "ነሃሴ", "ጳጉሜ"};
    public int Date, Month, Year;
    EthiopianCalendar ec;

    /**
     * Creates new form DateConverter
     *
     * @param parent
     * @param modal
     */
    public DateConverter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        int parentWidth = parent.getWidth();
        int parentX = parent.getX();
        int parentHeight = parent.getHeight();
        int parentY = parent.getY();

        setLocation((parentWidth / 2) - (getWidth() / 2) + parentX, (parentHeight / 2) - (getHeight() / 2) + parentY);
        Calendar c = Calendar.getInstance();
        EthiopianCalendar ec=new EthiopianCalendar();
        int ethiopic[] = ec.toEthiopicDate(c);
        int date = ec.formattedDate(ethiopic[0], ethiopic[1])[0];
        int month = ec.formattedDate(ethiopic[0], ethiopic[1])[1];
        int year = ec.formattedDate(ethiopic[0], ethiopic[1])[2];
        if (ec.isToday(date, month, year)) {
            monthEnter.setSelectedIndex(month - 1);
            yearEnter.setValue(year);
            dateEnter.setValue(date);
            ec.getMonthFormat(ec.toNumberDay(date, month, year), year);
            Year = year;
            Month = month;
            Date = date;
            Calendar gc = ec.toGregorianDate(Date, Month, Year);
            gregoriandate.setText(gc.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.ENGLISH) + " - " + gc.get(Calendar.DAY_OF_MONTH) + " - " + gc.get(Calendar.YEAR));

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internal = new javax.swing.JInternalFrame();
        dateConverterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        monthEnter = new javax.swing.JComboBox(MONTHS);
        dateEnter = new javax.swing.JSpinner();
        find = new javax.swing.JButton();
        yearEnter = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        gregoriandate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ወደ ጎርጎርዮሳዊያን ቀን መቁጠሪያ");
        setResizable(false);

        internal.setBorder(null);
        internal.setVisible(false);

        javax.swing.GroupLayout internalLayout = new javax.swing.GroupLayout(internal.getContentPane());
        internal.getContentPane().setLayout(internalLayout);
        internalLayout.setHorizontalGroup(
            internalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        internalLayout.setVerticalGroup(
            internalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dateConverterPanel.setName("dateConverterPanel"); // NOI18N
        dateConverterPanel.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 1));
        jLabel2.setText("ዓመት :");

        monthEnter.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        monthEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthEnterActionPerformed(evt);
            }
        });

        dateEnter.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        dateEnter.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        dateEnter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateEnterFocusGained(evt);
            }
        });

        find.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        find.setText("ፈልግ");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        yearEnter.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        yearEnter.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2008), Integer.valueOf(0), null, Integer.valueOf(1)));
        yearEnter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearEnterFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 1));
        jLabel3.setText("ወር :");

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 1));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("የጎርጎርዮሳዊያን ቀን");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 1));
        jLabel4.setText("ቀን :");

        gregoriandate.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        gregoriandate.setForeground(new java.awt.Color(0, 0, 1));
        gregoriandate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout dateConverterPanelLayout = new javax.swing.GroupLayout(dateConverterPanel);
        dateConverterPanel.setLayout(dateConverterPanelLayout);
        dateConverterPanelLayout.setHorizontalGroup(
            dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dateConverterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dateConverterPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(find))
                    .addGroup(dateConverterPanelLayout.createSequentialGroup()
                        .addGroup(dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGroup(dateConverterPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4)))
                        .addGap(31, 31, 31)
                        .addGroup(dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateEnter)
                            .addComponent(yearEnter)
                            .addComponent(monthEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dateConverterPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(gregoriandate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dateConverterPanelLayout.setVerticalGroup(
            dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dateConverterPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dateConverterPanelLayout.createSequentialGroup()
                        .addGroup(dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(yearEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(monthEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dateConverterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dateEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(find))
                    .addGroup(dateConverterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(gregoriandate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(internal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(dateConverterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(dateConverterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(internal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        int year = (int) yearEnter.getValue();
        int month = 1 + monthEnter.getSelectedIndex();
        int date = (int) dateEnter.getValue();
        ec = new EthiopianCalendar();
        Calendar c = ec.toGregorianDate(date, month, year);
        gregoriandate.setText(c.getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.ENGLISH) + " - " + c.get(Calendar.DAY_OF_MONTH) + " - " + c.get(Calendar.YEAR));

    }//GEN-LAST:event_findActionPerformed

    private void yearEnterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearEnterFocusGained
        Year = (int) yearEnter.getValue();
    }//GEN-LAST:event_yearEnterFocusGained

    private void dateEnterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateEnterFocusGained
        Date = (int) dateEnter.getValue();
    }//GEN-LAST:event_dateEnterFocusGained

    private void monthEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthEnterActionPerformed
        ec = new EthiopianCalendar();
        Month = monthEnter.getSelectedIndex();
        if (monthEnter.getSelectedIndex() == 12) {
            if (ec.isLeapYear((int) yearEnter.getValue())) {
                dateEnter.setModel(new javax.swing.SpinnerNumberModel(1, 1, 6, 1));
            } else {
                dateEnter.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
            }
        } else {
            dateEnter.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));
        }
    }//GEN-LAST:event_monthEnterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel dateConverterPanel;
    private javax.swing.JSpinner dateEnter;
    private javax.swing.JButton find;
    private javax.swing.JLabel gregoriandate;
    private javax.swing.JInternalFrame internal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox monthEnter;
    private javax.swing.JSpinner yearEnter;
    // End of variables declaration//GEN-END:variables
}
