/*
 * Copyright (C) 2016 Tadesse Angaw
 *
 * This program is written by Tadesse Angaw.
 * You can use and redistribute it without modification.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You can contact me at tadesseangaw@gmail.com
 */
package com.tadesse.bahirehasab.app;

import java.awt.Frame;
import com.tadesse.bahirehasab.tools.EthiopianCalendar;

/**
 *
 * @author Tadesse Angaw
 */
public class Fasting extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    String FAST_NAMES[] = {"ጽጌ ጾም", "ጾመ ነቢያት (የገና ጾም)", "ጾመ ጋድ", "ጾመ ነነዌ", "ዐቢይ ጾም (ጾመ ሁዳዴ)", "ጾመ ሐዋርያት (የሰኔ ጾም)", "ጾመ ድኅነት (ረቡዕ እና አርብ)", "ጾመ ፍልሰታ"};
    EthiopianCalendar ec;
    int Year;
    int[] FAST = new int[8];

    /**
     * Creates new form Fasting
     *
     * @param parent
     * @param modal
     * @param year
     */
    public Fasting(java.awt.Frame parent, boolean modal, int year) {
        super(parent, modal);
        initComponents();
        this.Year = year;
        fastingBuilder(year);
        int x = parent.getX();
        int y = parent.getY();
        int width = parent.getWidth();
        int height = parent.getHeight();
        setLocation((width / 2) - (this.getWidth() / 2), (height / 2) - (this.getWidth() / 2));

    }

    public Fasting() {

    }

    public void fastingBuilder(int year) {
        ec = new EthiopianCalendar();
        this.year.setText("" + year);
        setTitle("" + year);
        tsge.setText(ec.getMonthFormat(ec.getTsege(), year));
        gena.setText(ec.getMonthFormat(ec.getTsomeNebiyat(), year));
        if (ec.getGad(year) != -1) {
            gad.setText(ec.getMonthFormat(ec.getGad(year), year));
        } else {
            gad.setText("የለውም");
        }

        nenewe.setText(ec.getMonthFormat(ec.getNenewe(year), year));
        abey.setText(ec.getMonthFormat(ec.getAbeyTsome(year), year));
        sene.setText(ec.getMonthFormat(ec.getTsomeHawariyat(year), year));
        robarb.setText(ec.getMonthFormat(ec.getTsomeDihnet(year), year));
        felseta.setText(ec.getMonthFormat(ec.getFelseta(), year));

    }

    public boolean isFastStarting(int day, int year) {
        getFasting(year);
        for (int i = 0; i < FAST.length; i++) {
            if (day == FAST[i]) {
                return true;
            }
        }
        return false;
    }

    public void getFasting(int year) {
        ec = new EthiopianCalendar();
        FAST[0] = ec.getTsege();
        FAST[1] = ec.getTsomeNebiyat();
        FAST[2] = ec.getGad(year);
        FAST[3] = ec.getNenewe(year);
        FAST[4] = ec.getAbeyTsome(year);
        FAST[5] = ec.getTsomeHawariyat(year);
        FAST[6] = ec.getTsomeDihnet(year);
        FAST[7] = ec.getFelseta();
    }

    public String getFastingDescription(int day, int year) {
        getFasting(year);
        for (int i = 0; i < FAST.length; i++) {
            if (day == FAST[i]) {
                return FAST_NAMES[i];
            }
        }
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fastingPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        year = new javax.swing.JLabel();
        tsge = new javax.swing.JLabel();
        gena = new javax.swing.JLabel();
        gad = new javax.swing.JLabel();
        nenewe = new javax.swing.JLabel();
        abey = new javax.swing.JLabel();
        sene = new javax.swing.JLabel();
        robarb = new javax.swing.JLabel();
        felseta = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        previous = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fastingPanel.setName("fastingPanel"); // NOI18N
        fastingPanel.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 1));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ጽጌ ጾም");

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 1));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ጾመ ነቢያት (የገና ጾም)");

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 1));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ጾመ ጋድ");

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 1));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ጾመ ነነዌ");

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 1));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("ዓቢይ ጾም");

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 1));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ጾመ ሐዋርያት (የሰኔ ጾም)");

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 1));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("ጾመ ድኅነት (ረቡዕ እና አርብ)");

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 1));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("ጾመ ፍልሰታ");

        year.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        year.setForeground(new java.awt.Color(0, 0, 1));
        year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        year.setText("Year");

        tsge.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        tsge.setForeground(new java.awt.Color(0, 0, 1));
        tsge.setText("00");

        gena.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        gena.setForeground(new java.awt.Color(0, 0, 1));
        gena.setText("00");

        gad.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        gad.setForeground(new java.awt.Color(0, 0, 1));
        gad.setText("00");

        nenewe.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        nenewe.setForeground(new java.awt.Color(0, 0, 1));
        nenewe.setText("00");

        abey.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        abey.setForeground(new java.awt.Color(0, 0, 1));
        abey.setText("00");

        sene.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        sene.setForeground(new java.awt.Color(0, 0, 1));
        sene.setText("00");

        robarb.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        robarb.setForeground(new java.awt.Color(0, 0, 1));
        robarb.setText("00");

        felseta.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        felseta.setForeground(new java.awt.Color(0, 0, 1));
        felseta.setText("00");

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/resource/right.png"))); // NOI18N
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/resource/left.png"))); // NOI18N
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fastingPanelLayout = new javax.swing.GroupLayout(fastingPanel);
        fastingPanel.setLayout(fastingPanelLayout);
        fastingPanelLayout.setHorizontalGroup(
            fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fastingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fastingPanelLayout.createSequentialGroup()
                        .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 36, Short.MAX_VALUE)
                        .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gena, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nenewe, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abey, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sene, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(robarb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(felseta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tsge, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fastingPanelLayout.createSequentialGroup()
                        .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        fastingPanelLayout.setVerticalGroup(
            fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fastingPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(previous, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(year, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tsge, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gena, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(gad, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nenewe, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(abey, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sene, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(robarb, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fastingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(felseta, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fastingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fastingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if (Year != 9999) {
            Year += 1;
            fastingBuilder(this.Year);
        } else {
            EndTwo end2 = new EndTwo((Frame) this.getParent(), true);
            end2.setVisible(true);
        }

    }//GEN-LAST:event_nextActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        if (Year != 0) {
            Year -= 1;
            fastingBuilder(this.Year);
        } else {
            EndOne end1 = new EndOne((Frame) this.getParent(), true);
            end1.setVisible(true);
        }

    }//GEN-LAST:event_previousActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abey;
    public javax.swing.JPanel fastingPanel;
    private javax.swing.JLabel felseta;
    private javax.swing.JLabel gad;
    private javax.swing.JLabel gena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nenewe;
    private javax.swing.JButton next;
    private javax.swing.JButton previous;
    private javax.swing.JLabel robarb;
    private javax.swing.JLabel sene;
    private javax.swing.JLabel tsge;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
