/*
 * Copyright (C) 2016 Tadesse Angaw
 *
 * This program is written by Tadesse Angaw.
 * You can use and redistribute it without modification.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You can contact me at tadesseangaw@gmail.com
 */
package com.tadesse.bahirehasab.app;

import java.awt.Frame;
import com.tadesse.bahirehasab.tools.EthiopianCalendar;

/**
 *
 * @author Tadesse Angaw
 */
public class Holiday extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    EthiopianCalendar ec;
    public String[] HOLYDAYS_NAME = {"ፅንሰት", "ልደት", "ጥምቀት", "ሆሳዕና", "ስቅለት", "ትንሳኤ", "ዕርገት", "ጰራቅሊጦስ", "ደብረ ታቦር"};

    int[] HOLYDAYS = new int[9];
    int Year;

    /**
     * Creates new form Holiday
     *
     * @param parent
     * @param modal
     * @param year
     */
    public Holiday(java.awt.Frame parent, boolean modal, int year) {
        super(parent, modal);
        initComponents();
        this.Year = year;
        holydayBuilder(year);
        int parentWidth = parent.getWidth();
        int parentX = parent.getX();
        int parentHeight = parent.getHeight();
        int parentY = parent.getY();

        setLocation((parentWidth / 2) - (getWidth() / 2) + parentX, (parentHeight / 2) - (getHeight() / 2) + parentY);
    }

    public Holiday() {
        
    }

    public void holydayBuilder(int year) {
        this.year.setText("" + year);
        setTitle("" + year);
        mainHolydays(year);
        miniHolydays(year);
//        otherHolydays(year);
    }

    public void mainHolydays(int year) {
        ec = new EthiopianCalendar();
        tsnset.setText(ec.getMonthFormat(209, year));
        lidet.setText(ec.getMonthFormat(ec.getGena(year), year));
        timket.setText(ec.getMonthFormat(ec.getTimket(), year));
        hosaena.setText(ec.getMonthFormat(ec.getHosaena(year), year));
        siqlet.setText(ec.getMonthFormat(ec.getSiqlet(year), year));
        tinsae.setText(ec.getMonthFormat(ec.getTinsae(year), year));
        erget.setText(ec.getMonthFormat(ec.getErget(year), year));
        peraklitos.setText(ec.getMonthFormat(ec.getPeraklitos(year), year));
        debretabor.setText(ec.getMonthFormat(343, year));
    }

    public void miniHolydays(int year) {
        ec = new EthiopianCalendar();
        sibket.setText(ec.getMonthFormat(ec.getSibket(year), year));
        birhan.setText(ec.getMonthFormat(ec.getBirhan(year), year));
        nolawi.setText(ec.getMonthFormat(ec.getNolawi(year), year));
        gezret.setText(ec.getMonthFormat(126, year));
        lidetesimon.setText(ec.getMonthFormat(158, year));
        kana.setText(ec.getMonthFormat(132, year));
        debrezeit.setText(ec.getMonthFormat(ec.getDebreZeit(year), year));
        meskel1.setText(ec.getMonthFormat(190, year));
    }

    public boolean isHolyday(int date, int month, int year) {
        ec = new EthiopianCalendar();
        int day = ec.toNumberDay(date, month, year);
        getHolydays(year);
        for (int i = 0; i < HOLYDAYS.length; i++) {
            if (day == HOLYDAYS[i]) {
                return true;
            }
        }
        return false;
    }

    public String getHolydayDescription(int date, int month, int year) {
        ec = new EthiopianCalendar();
        if (isHolyday(date, month, year)) {
            String description = "";
            String another = "፣ ";
            int day = ec.toNumberDay(date, month, year);
            for (int i = 0; i < HOLYDAYS.length; i++) {
                if (day == HOLYDAYS[i]) {
                    if (description.equals("")) {
                        description = HOLYDAYS_NAME[i];
                    } else {
                        description += another + HOLYDAYS_NAME[i];
                    }
                }
            }
            return description;
        } else {
            return "";
        }
    }

    public void getHolydays(int year) {
        ec = new EthiopianCalendar();
        HOLYDAYS[0] = 209;
        HOLYDAYS[1] = ec.getGena(year);
        HOLYDAYS[2] = ec.getTimket();
        HOLYDAYS[3] = ec.getHosaena(year);
        HOLYDAYS[4] = ec.getSiqlet(year);
        HOLYDAYS[5] = ec.getTinsae(year);
        HOLYDAYS[6] = ec.getErget(year);
        HOLYDAYS[7] = ec.getPeraklitos(year);
        HOLYDAYS[8] = 343;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holydayPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        l112 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        tsnset = new javax.swing.JLabel();
        lidet = new javax.swing.JLabel();
        timket = new javax.swing.JLabel();
        siqlet = new javax.swing.JLabel();
        tinsae = new javax.swing.JLabel();
        erget = new javax.swing.JLabel();
        peraklitos = new javax.swing.JLabel();
        debretabor = new javax.swing.JLabel();
        hosaena = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        previous = new javax.swing.JButton();
        year = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        l113 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        l22 = new javax.swing.JLabel();
        l23 = new javax.swing.JLabel();
        l24 = new javax.swing.JLabel();
        l25 = new javax.swing.JLabel();
        l26 = new javax.swing.JLabel();
        birhan = new javax.swing.JLabel();
        nolawi = new javax.swing.JLabel();
        gezret = new javax.swing.JLabel();
        kana = new javax.swing.JLabel();
        debrezeit = new javax.swing.JLabel();
        meskel1 = new javax.swing.JLabel();
        lidetesimon = new javax.swing.JLabel();
        l115 = new javax.swing.JLabel();
        sibket = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("የበዓላት ማውጫ");
        setResizable(false);

        holydayPanel.setName("holydayPanel"); // NOI18N
        holydayPanel.setOpaque(false);

        jPanel4.setForeground(new java.awt.Color(0, 0, 1));
        jPanel4.setOpaque(false);

        l112.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l112.setForeground(new java.awt.Color(0, 0, 1));
        l112.setText("ፅንሰት");

        l13.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l13.setForeground(new java.awt.Color(0, 0, 1));
        l13.setText("ልደት");

        l14.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l14.setForeground(new java.awt.Color(0, 0, 1));
        l14.setText("ጥምቀት");

        l15.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l15.setForeground(new java.awt.Color(0, 0, 1));
        l15.setText("ሆሳዕና");

        l16.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l16.setForeground(new java.awt.Color(0, 0, 1));
        l16.setText("ስቅለት");

        l17.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l17.setForeground(new java.awt.Color(0, 0, 1));
        l17.setText("ትንሳኤ");

        l18.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l18.setForeground(new java.awt.Color(0, 0, 1));
        l18.setText("ዕርገት");

        l19.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l19.setForeground(new java.awt.Color(0, 0, 1));
        l19.setText("ጰራቅሊጦስ");

        l20.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l20.setForeground(new java.awt.Color(0, 0, 1));
        l20.setText("ደብረ ታቦር");

        tsnset.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        tsnset.setForeground(new java.awt.Color(0, 0, 1));
        tsnset.setText("0000");

        lidet.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        lidet.setForeground(new java.awt.Color(0, 0, 1));
        lidet.setText("0000");

        timket.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        timket.setForeground(new java.awt.Color(0, 0, 1));
        timket.setText("0000");

        siqlet.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        siqlet.setForeground(new java.awt.Color(0, 0, 1));
        siqlet.setText("0000");

        tinsae.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        tinsae.setForeground(new java.awt.Color(0, 0, 1));
        tinsae.setText("0000");

        erget.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        erget.setForeground(new java.awt.Color(0, 0, 1));
        erget.setText("0000");

        peraklitos.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        peraklitos.setForeground(new java.awt.Color(0, 0, 1));
        peraklitos.setText("0000");

        debretabor.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        debretabor.setForeground(new java.awt.Color(0, 0, 1));
        debretabor.setText("0000");

        hosaena.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        hosaena.setForeground(new java.awt.Color(0, 0, 1));
        hosaena.setText("0000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(l13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tsnset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lidet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hosaena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(siqlet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(erget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(peraklitos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(debretabor, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(tinsae, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tsnset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lidet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hosaena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(siqlet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tinsae, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(erget)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(peraklitos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(debretabor))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(l112)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l20))))
        );

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/resource/right.png"))); // NOI18N
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/resource/left.png"))); // NOI18N
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        year.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        year.setForeground(new java.awt.Color(0, 0, 1));
        year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        year.setText("Year");

        jPanel5.setForeground(new java.awt.Color(0, 0, 1));
        jPanel5.setOpaque(false);

        l113.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l113.setForeground(new java.awt.Color(0, 0, 1));
        l113.setText("ብርሃን");

        l21.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l21.setForeground(new java.awt.Color(0, 0, 1));
        l21.setText("ኖላዊ ");

        l22.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l22.setForeground(new java.awt.Color(0, 0, 1));
        l22.setText("ግዝረት");

        l23.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l23.setForeground(new java.awt.Color(0, 0, 1));
        l23.setText("ልደተ ስምዖን");

        l24.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l24.setForeground(new java.awt.Color(0, 0, 1));
        l24.setText("ቃና ዘገሊላ");

        l25.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l25.setForeground(new java.awt.Color(0, 0, 1));
        l25.setText("ደብረዘይት");

        l26.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l26.setForeground(new java.awt.Color(0, 0, 1));
        l26.setText("መስቀል");

        birhan.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        birhan.setForeground(new java.awt.Color(0, 0, 1));
        birhan.setText("0000");

        nolawi.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        nolawi.setForeground(new java.awt.Color(0, 0, 1));
        nolawi.setText("0000");

        gezret.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        gezret.setForeground(new java.awt.Color(0, 0, 1));
        gezret.setText("0000");

        kana.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        kana.setForeground(new java.awt.Color(0, 0, 1));
        kana.setText("0000");

        debrezeit.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        debrezeit.setForeground(new java.awt.Color(0, 0, 1));
        debrezeit.setText("0000");

        meskel1.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        meskel1.setForeground(new java.awt.Color(0, 0, 1));
        meskel1.setText("0000");

        lidetesimon.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        lidetesimon.setForeground(new java.awt.Color(0, 0, 1));
        lidetesimon.setText("0000");

        l115.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        l115.setForeground(new java.awt.Color(0, 0, 1));
        l115.setText("ስብከት ");

        sibket.setFont(new java.awt.Font("Ebrima", 1, 11)); // NOI18N
        sibket.setForeground(new java.awt.Color(0, 0, 1));
        sibket.setText("0000");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(l21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l115, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sibket, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(birhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nolawi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gezret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lidetesimon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(debrezeit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(meskel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sibket)
                    .addComponent(l115))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(birhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nolawi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gezret)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lidetesimon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(debrezeit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(meskel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(l113)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout holydayPanelLayout = new javax.swing.GroupLayout(holydayPanel);
        holydayPanel.setLayout(holydayPanelLayout);
        holydayPanelLayout.setHorizontalGroup(
            holydayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(holydayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(holydayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(holydayPanelLayout.createSequentialGroup()
                        .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(holydayPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        holydayPanelLayout.setVerticalGroup(
            holydayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(holydayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(holydayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next)
                    .addComponent(previous))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(holydayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, holydayPanelLayout.createSequentialGroup()
                        .addGroup(holydayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, holydayPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(holydayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(holydayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        if (Year != 0) {
            if (this.Year > 0) {
                Year -= 1;
                holydayBuilder(this.Year);
            }
        } else {
            EndOne end1 = new EndOne((Frame) this.getParent(), true);
            end1.setVisible(true);
        }
    }//GEN-LAST:event_previousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if (Year != 9999) {
            Year += 1;
            holydayBuilder(this.Year);
        } else {
            EndTwo end2 = new EndTwo((Frame) this.getParent(), true);
            end2.setVisible(true);
        }
    }//GEN-LAST:event_nextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birhan;
    private javax.swing.JLabel debretabor;
    private javax.swing.JLabel debrezeit;
    private javax.swing.JLabel erget;
    private javax.swing.JLabel gezret;
    public javax.swing.JPanel holydayPanel;
    private javax.swing.JLabel hosaena;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel kana;
    private javax.swing.JLabel l112;
    private javax.swing.JLabel l113;
    private javax.swing.JLabel l115;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l22;
    private javax.swing.JLabel l23;
    private javax.swing.JLabel l24;
    private javax.swing.JLabel l25;
    private javax.swing.JLabel l26;
    private javax.swing.JLabel lidet;
    private javax.swing.JLabel lidetesimon;
    private javax.swing.JLabel meskel1;
    private javax.swing.JButton next;
    private javax.swing.JLabel nolawi;
    private javax.swing.JLabel peraklitos;
    private javax.swing.JButton previous;
    private javax.swing.JLabel sibket;
    private javax.swing.JLabel siqlet;
    private javax.swing.JLabel timket;
    private javax.swing.JLabel tinsae;
    private javax.swing.JLabel tsnset;
    private javax.swing.JLabel year;
    // End of variables declaration//GEN-END:variables
}
