/*
 * Copyright (C) 2016 Tadesse Angaw
 *
 * This program is written by Tadesse Angaw.
 * You can use and redistribute it without modification.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You can contact me at tadesseangaw@gmail.com
 */
package com.tadesse.bahirehasab.help;

import java.awt.Insets;
import java.awt.Toolkit;

/**
 *
 * @author Tadesse Angaw
 */
public class Help extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Help
     *
     * @param parent
     * @param modal
     */
    public Help(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        int height = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarHeight = scnMax.bottom;
        setSize(getWidth(), height-taskBarHeight);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(" አጠቃቀም");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 1));
        jLabel1.setText("<html>ይህ ሶፍትዌር በኢትዮጵያ ኦርቶዶክስ ተዋህዶ ቤተክርስቲያን ላለፉት ዘመናት ሲሠራበት የነበረውን<br>የባሕረ ሐሳብ ቀመር መሠረት በማድረግ ለአጽዋማት እና ለበዓላት ማውጫ እንዲሆን የተዘጋጀ ነው::</html>");

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 1));
        jLabel2.setText("<html><h2>1 መረጃ ማስገቢያ </h2> ይህ ስፍራ የምንፈልጋቸውን አጽዋማትም ሆነ በዓላትን ለማግኘት በቅድሚያ በዓላቱም ሆነ አጽዋማቱ<br>  የሚውሉበትን ዓመት እንዲሁም የቀን ማውጫውን ለመጠቀም የምንፈልገውን ቀን፣ ወር እና ዓመት<br> ለመሙላት የሚያስችለን ስፍራ ነው::  <h2>2 ሰዓት እና ቀን ማሳያ</h2>  ይህ ቦታ የኮምፒውተሩን ሰዓት እና ቀን ማሳያ ስፍራ ነው:: ሰዓቱ በግዕዝ ቁጥሮች የሚታይ ሲሆን<br>  ከአጠገቡ የተለመደው የሰዓት መቁጠሪያ ይታያል::በተጨማሪም ዛሬ ቀኑ፣ ወሩን እና ዓመቱ ስንት <br>  እንደሆነ ይገልፃል:: በሰማያዊ ቀለም የሚታየውን ጽሑፍ በተጫኑት ጊዜ መረጃ ማስገቢያው እና<br>  ውጤት ማሳያው ወደዛሬ ይስተካከላሉ::<br>  <h4>&nbsp&nbsp&nbsp<p style='text-decoration: underline'>ማሳሰቢያ:<p></h4>  &nbsp&nbsp&nbspየኮምፒውተርዎ ቀንእና ሰዓት በአግባቡ ካልተሞላ ይህ ሶፍትዌር የሚያሳየው የተሳሳተ ቀን እና<br>  &nbsp&nbsp&nbspሰዓት ስለሚሆን የኮምፒውተርዎን ቀንና ሰዓት በአግባቡ መሞላቱን ያረጋግጡ::<br>  <h2>3 አማራጮች</h2>  ከላይ ላስገቡት መረጃ የሚፈልጉት ውጤት ምን እንደሆነ የሚመርጡት በዚህ ስፍራ ነው::<br>  <h2>4 ውጤት ማሳያ</h2>  ሶፍትዌሩ ሲከፈት ውጤት ማሳያው ላይ የሚታየው የቀን ማውጫ ሲሆን የአጽዋማት እና መሠረታዊ<br>  መረጃዎች የሚታዩትም በዚህ ቦታ ላይ ነው:: ነገር ግን የበዓላት ማውጫ፣ 33ቱ የእመቤታችን<br>  በዓላት በዚህ ስፍራ ሳይሆን ለብቻቸው የሚታዩ ይሆናል::<br> </html> ");

        jLabel16.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Main.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2173, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab("አጠቃላይ", jScrollPane1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 1));
        jLabel4.setText("<html> ይህ የቀን ማውጫ በኢትዮጵያውያን የዘመን ቀመር የሚቆጥር ሲሆን በመረጃ ማስገቢያው ላይ የገባለትን<br>  ዓመት ወር እና ቀን የሚያሳይ ይሆናል:: በአንድ ጊዜ የሚታየው የአንድ ወር ማውጫ ብቻ ሲሆን ወደ ግራ <br>  እና ቀኝ አቅጣጫ የሚያመላክቱትን ቁልፎች በመጫን ቀን ማውጫው እያሳየ ከሚገኘው ወር ቀድሞ ወይም<br>  ቀጥሎ የሚገኝውን ወር ማግኘት ወይም ማየት ይቻላል:: ሶፍትዌሩን ገና እንዳስጀመሩት የሚታየው የቀን<br>  ማውጫ የዛሬ ቀን የሚገኝበት ወር እና ዓመት ሲሆን በመረጃ ማስገቢያው ላይ የምንፈልገውን ዓመት፣ ወር<br>  እና ቀን በመሙላት እንዲሁም ቀን ማውጫ የሚለውን አማራጭ በመጫን የምንፈልገውን ቀን መመልከት<br>  እንችላለን:: ቀን ማውጫው በግዕዝ ቁጥሮችም ቀኖችን ያሳያል::<br>   <br>  <h4>ተጨማሪ<h4>  <ul>  <li>ቀን ማውጫው ሳምንቱን የሚጀምረው በእሑድ ነው::</li>  <li>እሑድ የሚውሉ ቀናት በሙሉ በቀይ ቀለም ይጻፋሉ::</li>  <li>በብርቱካናማ ቀለም ጀርባው የደመቀ ቀን ዛሬን ያመላክታል::</li>  <li>በፈዛዛ አረንጓዴ ቀለም ጀርባቸው የደመቁ ቀናት የጌታችን ዓበይት በዓላት የሚውሉባቸው ቀናት ናቸው::</li>  <li>የጌታችን ዓበይት በዓላት የሆኑ ቀኖች ላይ ስንጫን ከቀን ማውጫው ዝቅ ብሎ ምን በዓል እንደሚከበር ያሳየናል::  </li>  <li>በቀን ማውጫው ላይ የሚታዩ ቀኖች ላይ የኮምፒውተራችንን ጠቋሚ (Mouse pointer) በማስጠጋት፣ ባስጠጋነው ቀን ላይ ታስበው የሚውሉ ቅዱሳንን ማየት ይቻላል::</li>  </ul>  </html>");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Calendar 1.PNG"))); // NOI18N

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Calendar 2.PNG"))); // NOI18N

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Calendar 3.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        jTabbedPane1.addTab("ቀን ማውጫ", jScrollPane2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 1));
        jLabel5.setText("<html>  በዓመቱ ውስጥ የሚከበሩትን ዋና ዋና በዓላትን ማሳያ ስፍራ ሲሆን፣ በዓላቱን ለሁለት በመክፈል የጌታችንን ዐበይት እና ንዑሳን በዓላትን በማለት በዓላቱ የሚውሉበትን ቀን አካትቶ ይዟል::: ከዚህ በተጨማሪ ወደግራ እና ቀኝ የሚጠቁሙትን ቁልፎች በመጫን  የበዓላት ማውጫው ከሚገኝበት ዓመት ቀድሞ ወይም ቀጥሎ የሚገኘውን ዓመት በዓላት ማየት ይቻላል:: </html>");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Holyday.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2578, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel3);

        jTabbedPane1.addTab("የበዓላት ማውጫ", jScrollPane3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 1));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>   የአጽዋማት ማውጫው በመረጃ ማስገቢያው ላይ በጨመርነው ዓመት ውስጥ የጽጌ ጾምን እና ሰባቱን የአዋጅ  አጽዋማት የሚገቡበትን ቀን እና ዕለት ማሳያ ስፍራ ነው:: ወደግራ እና ቀኝ የሚጠቁሙትን ቁልፎች በመጫን  የአጽዋማት ማውጫው ከሚገኝበት ዓመት ቀድሞ ወይም ቀጥሎ የሚገኘውን ዓመት ማየት ይቻላል::  <h4>ተጨማሪ</h4> <ul> <li>በተጠቀሰው ዓመት ውስጥ የጥምቀት በዓል ረቡዕ ወይም አርብ ቀን የማይውል ከሆነ ጾመ ጋድ ስለማይጾም ሶፍትዌሩ የለውም የሚል ጽሑፍ ያሳያል::</li> </ul> </html>");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Fasting.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2492, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel4);

        jTabbedPane1.addTab("የአጽዋማት ማውጫ", jScrollPane4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 1));
        jLabel9.setText("<html>  \nየዓመቱ መሠረታዊ መ ረጃዎች የሚታዩበት ሥፍራ ሲሆን መጥቅዕ፣ አበቅቴ፣ የዓመቱ መጀመሪያ ቀን እና ሌሎችም ይካተቱበታል:: ወደግራ እና ቀኝ የሚጠቁሙትን ቁልፎች በመጫን መሠረታዊ መረጃዎች ከሚገኝበት ዓመት ቀድሞ ወይም ቀጥሎ የሚገኘውን ዓመት ማየት ይቻላል::\n</html>");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Basic.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2583, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel5);

        jTabbedPane1.addTab("መሠረታዊ መረጃዎች", jScrollPane5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 1));
        jLabel11.setText("<html>  እመቤታችን ቅድስት ድንግል ማርያም በዓመት ውስጥ የሚከበሩ ሠላሳ ሦስት በዓላት አሏት::  ይህ ሶፍትዌርም በመረጃ ማስገቢያው ላይ  በጨመርነው ዓመት ውስጥ የሚገኙትን የእመቤታችንን በዓላት ለሦስት (ከመስከረም - ጥር፣ ከየካቲት - ግንቦት እና ከሰኔ - ነሐሴ) በመክፈል ያሳያል::  ወደግራ እና ቀኝ የሚጠቁሙትን ቁልፎች በመጫን በዓላቱ ከሚገኙበት ዓመት ቀድሞ ወይም ቀጥሎ የሚገኘውን ዓመት ማየት ይቻላል:: <h4>ተጨማሪ</h4>  <ul> <li>በዓላቱ የሚውሉበትን ቀናት የሚያሳየው ጽሑፍ ላይ ሄደን በመጫን ስለ በዓሉ አጭር ማብራሪያ ከጎኑ ማግኘት እንችላለን::</li> </ul> </html>");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/St. Marry 1.PNG"))); // NOI18N

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/St. Marry 2.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addContainerGap(2156, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jPanel6);

        jTabbedPane1.addTab("፴፫ቱ  የእመቤታችን በዓላት", jScrollPane6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 1));
        jLabel13.setText("<html> በኢትዮጵያውያን ቀን መቁጠሪያ የሰጠነውን ቀን ከአጠገቡ በጎርጎርዮሳውያን (Gregorian) ቀን መቁጠሪያ መልሶ የሚሰጥ ሲሆን መጀመሪያ እንደከፈትነው ዛሬ ላይ የሚጠቁም ይሆናል::  </html>");

        jLabel14.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/To Gregorian.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2593, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanel7);

        jTabbedPane1.addTab("ወደ ጎርጎርዮሳዊያን ቀን መቁጠሪያ", jScrollPane7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 1));
        jLabel18.setText("<html> <h2>ወደ ግዕዝ ቁጥር መቀየሪያ</h2> ይህ ሶፍትዌር ከሚሠራው ሥራ በተጨማሪ የተለመደውን የቁጥር አጻጻፍ ወደግዕዝ ቁጥር መቀየሪያም በውስጡ አካትቷል::  </html>");

        jLabel19.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 1));
        jLabel19.setText("<html> <h2>የእንኳን አደረሳችሁ መልዕክት</h2> የኮምፒውተርዎ ቀን በአግባቡ ከተሞላ በቀኑ ላይ ከጌታችን ዐበይት በዓላት መካከል አንዱ የሚውል ከሆነ ሶፍትዌሩን ገና እንደከፈቱት የእንኳን አደረሰዎ መልዕክት ይደርስዎታል:: </html>");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/To Ethiopic Number.PNG"))); // NOI18N

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Holyday Notification.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        jScrollPane8.setViewportView(jPanel8);

        jTabbedPane1.addTab("ተጨማሪ", jScrollPane8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 1));
        jLabel23.setText("<html>ይህ የቀን መቁጠሪያ ዋናው መተግበሪያ (Application) ላይ ካለው የቀን ማውጫ መጠነኛ ልዩነት ያለው ሲሆን በቀላሉ ወደሚፈልጉት ቀን እንዲሻገሩ ለማስቻል ከላይ የተቀመጠው የወር ስምና ዓመተ ምህረት ጽሑፍን መጫን ይችላሉ። ውጤቱም በመረጡት ዓመት ውስጥ ያሉትን ወራት ማሳያ ይሆናል። በድጋሚ ሌላ ዓመት ለማየት ከፈለጉ ከላይ የተቀመጠው የዓመት ጽሑፍን መጫን ይችላሉ። ዓመቱን መጫንዎ ውጤቱ ሌላ ዐሥር በመረጡት ዓመት አቅራቢያ ያሉ ዓመታትን ማሳያ ይሆናል። በዚህ ጊዜ ዐሥርቱ ዓመታትን የሚገልፅ ርዕስ ያገኛሉ። አሁንም የበለጠ ለመሄድ ከፈለጉ የዐሥርቱ ዓመታት ርዕስን ሲጫኑ የመቶ ዓመታት ማውጫ ያገኛሉ። <br/> ወደ ነበሩነት ለመመለስ የሚፈልጉትን ዓመት እና ወር ላይ እየተጫኑ  መመለስ ይችላሉ።</html>");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Tray View 1.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 1));
        jLabel25.setText("<html>ይህ በዓይነቱ ለየት ያለ የግርጌ ምልክት ኮምፒውተርዎ እንደተነሳ የሚጀምር ሲሆን ዘወትር ዋናውን መተግበሪያ (Application) መክፈት ሳያስፈልግዎ የቀኑን መሠረታዊ መረጃዎች ማግኘት ያስችልዎታል። ይህ ምልክት የሚገኘው በኮምፒውተርዎ የታችኛው ክፍል (Taskbar) ላይ ሲሆን የግርጌ ምልክቱም የዛሬን ቀን ያሳያል። ወደ ምልክቱ የኮምፒውተርዎን ጠቋሚ (Mouse pointer) ሲያስጠጉ በዛሬው ዕለት ታስበው የሚውሉ ቅዱሳንን ያሳያል። ከዚህ በተጨማሪ በዕለቱ ከጌታችን ዓበይት በዓላት ውስጥ አንዱ የሚከበር ከሆነ ምልክቱ ወደ ቀይ ይቀየራል</html>");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Tray View 2.png"))); // NOI18N

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Widget View 1.PNG"))); // NOI18N

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Tray View 3.png"))); // NOI18N

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Widget View 2.PNG"))); // NOI18N

        jLabel30.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 1));
        jLabel30.setText("<html><h1>2. የቀን መቁጠሪያ<h1></html>");

        jLabel31.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 1));
        jLabel31.setText("<html>ዛሬን ማሳያ ላይ የቀኝ ቁልፍዎን (Right click) በመጫን የተለያዩ አማራጮችን ማግኘት ይችላሉ። <br/><br/><ul><li>ቁጥር መቀየሪያ (በግዕዝ ወይም በአረብኛ)</li> <li>ከላይ ማስቀመጫ (ከማንኛውም የኮምፒውተርዎ መተግበሪያ (Application) በላይ ማድረጊያ)</li> <li>ቦታ መቀየሪያ (ግራ ወይም ቀኝ)</li><li>መውጫ (ዛሬን ማሳያውን መደበቂያ)</li> <ul></html>");

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Widget Change Number View.png"))); // NOI18N

        jLabel33.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 1));
        jLabel33.setText("<html><h1>1. ዛሬን ማሳያ<h1></html>");

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Mini Calendar 1.png"))); // NOI18N

        jLabel35.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 1));
        jLabel35.setText("<html>የግርጌ ምልክቱን ሲጫኑ ሦስት አማራጮች ይመጣሉ። የመጀመሪው ዛሬን ማሳያ (Widget) እንዲመጣልዎ ማዘዣ ሲሆን። ዛሬን ማሳያው በኮምፒውተርዎ የላይኛው ክፍል በመቀመጥ የዛሬን ቀን በግዕዝ አሊያም በተለመደው የአረብኛ ቁጥር ማሳየት ይችላል።ሁለኛው ደግሞ የቀን መቁጠሪያ ሲሆን በዋናው መተግበሪያ (Application) ላይ ካለው የቀን ማውጫ የተወሰኑ ነገሮች ተጨምረውበታል። የመጨረሻው ደግሞ መውጫ ነው። ይህም የግርጌ ምልክቱ እንዳይታይ ያደርጋል።</html>");

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Mini Calendar 2.png"))); // NOI18N

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Mini Calendar 4.png"))); // NOI18N

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Mini Calendar 3.png"))); // NOI18N

        jLabel39.setFont(new java.awt.Font("Ebrima", 0, 11)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 1));
        jLabel39.setText("<html> ጽጌ ጾምን ጨምሮ ሰባቱ  አጽዋማት ከመግግባታቸው ከሰባት ቀን ጀምሮ አጽዋማቱ ሊገቡ እንደሆነ ማሳወቂያ አለው</html>");

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/help/resource/Fasting Notification.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE))
                        .addGap(468, 468, 468))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(467, 467, 467))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(470, 470, 470))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))
                        .addGap(468, 468, 468))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(456, 456, 456))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                                .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addGap(37, 37, 37)
                .addComponent(jLabel26)
                .addGap(25, 25, 25)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel38)
                .addGap(29, 29, 29)
                .addComponent(jLabel37)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jScrollPane9.setViewportView(jPanel9);

        jTabbedPane1.addTab("የግርጌ ምልክት", jScrollPane9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
