/*
 * Copyright (C) 2016 Tadesse Angaw
 *
 * This program is written by Tadesse Angaw.
 * You can use and redistribute it without modification.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You can contact me at tadesseangaw@gmail.com
 */

package com.tadesse.bahirehasab.intro;

import javax.swing.JDialog;

/**
 *
 * @author Tadesse Angaw
 */
public class One extends javax.swing.JPanel {

    Two two;
    JDialog f;
    /**
     * Creates new form One
     * @param i
     */
    public One(Intro i) {
        initComponents();
        f=i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>\nበዚህ ሶፍትዌር በመጠቀም \n<ul>\n<li>የቀን ማውጫ</li>\n<li>የበዓላት ማውጫ</li>\n<li>የአጽዋማት ማውጫ</li>\n<li>የዓመታት መሠረታዊ መረጃዎች</li>\n<li>የእመቤታችን ቅድስት ድንግል ማርያም በዓላት የሚውሉበትን ቀናት</li>\n</ul>\nእንዲሁም ሌሎችን ለማወቅ ያስችላል::\n</html>\n");
        add(jLabel2);
        jLabel2.setBounds(10, 90, 550, 170);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ይህን ባሕረ ሐሳብ ሶፍትዌር ኮምፒውተርዎ ላይ ስለጫኑ እናመሰግናለን::");
        add(jLabel1);
        jLabel1.setBounds(0, 30, 570, 48);

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/resource/right.png"))); // NOI18N
        next.setOpaque(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        add(next);
        next.setBounds(520, 260, 40, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/resource/background.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 570, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        two=new Two((Intro) f);
        f.setContentPane(two);
        f.setSize(f.getWidth()-1, f.getHeight()-1);
        f.setSize(f.getWidth()+1, f.getHeight()+1);
    }//GEN-LAST:event_nextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
