/*
 * Copyright (C) 2016 Tadesse Angaw
 *
 * This program is written by Tadesse Angaw.
 * You can use and redistribute it without modification.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You can contact me at tadesseangaw@gmail.com
 */

package com.tadesse.bahirehasab.intro;

import javax.swing.JDialog;

/**
 *
 * @author Tadesse Angaw
 */
public class Two extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;

    One one;
    Three three;
    JDialog f;
    
    /**
     * Creates new form Two
     * @param i
     */
    public Two(Intro i) {
        initComponents();
        f=i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        previous = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/resource/left.png"))); // NOI18N
        previous.setOpaque(false);
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        add(previous);
        previous.setBounds(10, 260, 40, 30);

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/resource/right.png"))); // NOI18N
        next.setOpaque(false);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        add(next);
        next.setBounds(520, 260, 40, 30);

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("<html> በስሌቶች ላይ ለውጥ ባያመጣም ሶፍትዌሩ ትክክለኛውን ቀን እንዲያሳይዎ በቅድሚያ የኮምፒውተርዎን ቀንና ሰዓት በአግባቡ መሞላቱን ያረጋግጡ:: </html>");
        add(jLabel2);
        jLabel2.setBounds(70, 90, 430, 150);

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("በቅድሚያ ቀንና ሰዓትዎን ይሙሉ");
        add(jLabel3);
        jLabel3.setBounds(10, 20, 550, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/tadesse/bahirehasab/resource/background.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        one=new One((Intro) f);
        f.setContentPane(one);
        f.setSize(f.getWidth()-1, f.getHeight()-1);
        f.setSize(f.getWidth()+1, f.getHeight()+1);
    }//GEN-LAST:event_previousActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        three=new Three((Intro) f);
        f.setContentPane(three);
        f.setSize(f.getWidth()-1, f.getHeight()-1);
        f.setSize(f.getWidth()+1, f.getHeight()+1);
    }//GEN-LAST:event_nextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton next;
    private javax.swing.JButton previous;
    // End of variables declaration//GEN-END:variables
}
